name: Slušné správanie
favicon: null
layout_spectrum: 0.7914
typography_spectrum: 0.44043
title: Slušné správanie - séria kníh pre deti
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
